- hosts: localhost
  vars:
    rpmfusion_link: "https://download1.rpmfusion.org"
    fedora_version: "32"
    username: "sal"
  become: true

  tasks:
  - debug:
      msg:
      - "Using distribution: {{ ansible_distribution }}"
  
  - name: Enable RPMFusion
    dnf:
      name:
        - '{{ rpmfusion_link }}/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm' 
        - '{{ rpmfusion_link }}/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm'
      state: present
    when: ansible_distribution == "Fedora"
    when: '"Fedora" in ansible_distribution'
  
  - name: Update Fedora
    dnf:
      name: "*"
      state: latest
    when: '"Fedora" in ansible_distribution'

  - name: Update Debian
    apt:
      update_cache: yes
      cache_valid_time: 7200
      name: "*"
      state: latest
    when: '"Debian" in ansible_distribution or "Kali" in ansible_distribution'

  - name: Install packages
    package:
      name:
        - ssh
        - vim
        - git
        - zsh
        - gcc
        - g++
        - tor
        - fzf
        - curl
        - htop
        - gimp
        - gedit
        - python3
        - ipython3
        - nautilus
        - mitmproxy
        - keepassxc
        - terminator
        - firefox-esr
        - python3-pip
        - papirus-icon-theme
      state: latest
      
  - name: Enable SSH daemon in systemd
    systemd:
      name: sshd
      enabled: yes

  - name: Set zsh as default shell
    shell: "chsh --shell /usr/bin/zsh {{ username }}"

  - name: Download oh-my-zsh
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: oh-my-zsh-install.sh

  - name: Install oh-my-zsh
    shell: oh-my-zsh-install.sh >> oh-my-zsh.log

  # Example clone a repo with separate git directory
  - name: Clone my mini-projects repository
    git:
      repo: https://github.com/dzerus3/Mini-Projects.git
      dest: ~/workspace/Mini-Projects
      clone: yes

  - name: Copy files from foo to bar
    copy: 
      src:  ~/workspace/Mini-Projects/.zshrc
      dest: ~/.zshrc
